version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=zk
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ALLOWED_FILE_LINK_TYPES=pdf
      - DISABLE_POP_HOVER=false
      - SHOW_TOC=false
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
    volumes:
      - ./perlite/zk:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: jerivl/ellie-reverse-proxy:latest
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

